### ISSUE TITLE
[Bug]: Telescope layout_config conflict, cannot use vertical layout strategy

### ISSUE THREAD

**Issue by kraftnix** [chrisgrieser/nvim-scissors#28]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read [the docs, and in particular the FAQ](https://github.com/chrisgrieser/nvim-scissors#table-of-contents).
- [X] The problem is related to creating or editing snippets. (Expanding and using snippet is the responsibility of the snippet engine plugin, such as Luasnip or nvim-snippets.)

### Bug Description

Since the final telescope config uses a [tbl_deep_extend](https://github.com/chrisgrieser/nvim-scissors/blob/d65cde840766a7ccaf0d59326ad34c81f5ed40f7/lua/scissors/config.lua#L60) of `defaultConfig`, it seems impossible to set layout_strategy to `vertical`, [since setting](https://github.com/chrisgrieser/nvim-scissors//blob/d65cde840766a7ccaf0d59326ad34c81f5ed40f7/lua/scissors/config.lua#L33) `preview_width` when using a `vertical` strategy causes an error.

Is there a way to unset `preview_width`

### To Reproduce

Set `opts.telescope.opts.layout_strategy = "vertical"`.

You should get an error like
```
ScissorsEditSnippet Unsupported layout_config key for the vertical strategy: preview_width
```

### neovim version

```Text
0.11.0-dev
```

**Comment by chrisgrieser** [comment]
Fixed by #29

**Comment by kraftnix** [comment]
Ah, that change doesn't actually fix the issue unfortunately, it was purely informational since setting `layout_strategies` was a noop, and this change simply enforces that the `horizontal` strategy should be used.

The issue arises from the `tbl_deep_extend` call in [config.lua](https://github.com/chrisgrieser/nvim-scissors/blob/d65cde840766a7ccaf0d59326ad34c81f5ed40f7/lua/scissors/config.lua#L60), since you cannot unset `preview_width`, you cannot use the `vertical` layout strategy.

I didn't make a PR for this since, there are probably a few ways to allow this behaviour and I was unsure which you might want to do.

**Comment by chrisgrieser** [comment]
Ah, I see, right haven't thought of that. 

I mean, feel free to just make a PR that fixes that. Probably adding a one liner check that unsets preview_width when the layout isn't horizontal should be enough already
